//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corum.Models.ViewModels.ModelsResources", typeof(ModelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adresse.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intern kommentar.
        /// </summary>
        public static string AdminComment {
            get {
                return ResourceManager.GetString("AdminComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adresse er påkrevet.
        /// </summary>
        public static string AdressRequired {
            get {
                return ResourceManager.GetString("AdressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternativ 1.
        /// </summary>
        public static string Alternative1 {
            get {
                return ResourceManager.GetString("Alternative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternativ 1 er påkrevet.
        /// </summary>
        public static string Alternative1Required {
            get {
                return ResourceManager.GetString("Alternative1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternativ 2.
        /// </summary>
        public static string Alternative2 {
            get {
                return ResourceManager.GetString("Alternative2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beløp.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poststed.
        /// </summary>
        public static string Aria {
            get {
                return ResourceManager.GetString("Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poststed er påkrevet.
        /// </summary>
        public static string AriaRequired {
            get {
                return ResourceManager.GetString("AriaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fødselsdato.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fødselsdato er påkrevet.
        /// </summary>
        public static string BithdayIsRequired {
            get {
                return ResourceManager.GetString("BithdayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil 1 eiers navn.
        /// </summary>
        public static string Cellphone1ownerName {
            get {
                return ResourceManager.GetString("Cellphone1ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil1 er påkrevet.
        /// </summary>
        public static string Cellphone1Required {
            get {
                return ResourceManager.GetString("Cellphone1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil 2 eiers navn.
        /// </summary>
        public static string Cellphone2ownerName {
            get {
                return ResourceManager.GetString("Cellphone2ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil2 er påkrevet.
        /// </summary>
        public static string Cellphone2Required {
            get {
                return ResourceManager.GetString("Cellphone2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fornavn/Etternavn.
        /// </summary>
        public static string ChildName {
            get {
                return ResourceManager.GetString("ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kopier kursdeltakere.
        /// </summary>
        public static string CopyChildren {
            get {
                return ResourceManager.GetString("CopyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instruktør er påkrevet.
        /// </summary>
        public static string CourseInstructorRequired {
            get {
                return ResourceManager.GetString("CourseInstructorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instruktør.
        /// </summary>
        public static string CourseInstructors {
            get {
                return ResourceManager.GetString("CourseInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kurssted er påkrevet.
        /// </summary>
        public static string CourseLocationRequired {
            get {
                return ResourceManager.GetString("CourseLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kurssted.
        /// </summary>
        public static string CourseLocations {
            get {
                return ResourceManager.GetString("CourseLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kursnavn.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kursperiode.
        /// </summary>
        public static string CoursePeriods {
            get {
                return ResourceManager.GetString("CoursePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Navn er påkrevet.
        /// </summary>
        public static string CourseTypeNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CourseTypeNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kurstype er påkrevet.
        /// </summary>
        public static string CourseTypeRequired {
            get {
                return ResourceManager.GetString("CourseTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kurstype.
        /// </summary>
        public static string CourseTypes {
            get {
                return ResourceManager.GetString("CourseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukedag er påkrevet.
        /// </summary>
        public static string CourseWeekdayRequired {
            get {
                return ResourceManager.GetString("CourseWeekdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adresse.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fornavn/Etternavn.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postnr.
        /// </summary>
        public static string CustomerZip {
            get {
                return ResourceManager.GetString("CustomerZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Du må velge to forskjellige alternativ.
        /// </summary>
        public static string DifferentAlternatives {
            get {
                return ResourceManager.GetString("DifferentAlternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-post.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Melding.
        /// </summary>
        public static string EmailMessageBody {
            get {
                return ResourceManager.GetString("EmailMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-post er påkrevet.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emne.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feilmelding.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fra dato.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fra dato er påkrevet.
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aktiv.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maksimale antallet seter.
        /// </summary>
        public static string MaxSeatsCount {
            get {
                return ResourceManager.GetString("MaxSeatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seter er ikke-null verdi.
        /// </summary>
        public static string MaxSeatsCountRequired {
            get {
                return ResourceManager.GetString("MaxSeatsCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdi kan ikke overstige 10 tegn.
        /// </summary>
        public static string Name10LengthConstraint {
            get {
                return ResourceManager.GetString("Name10LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdi kan ikke overstige 20 tegn.
        /// </summary>
        public static string Name20LengthConstraint {
            get {
                return ResourceManager.GetString("Name20LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdi kan ikke overstige 255 tegn.
        /// </summary>
        public static string Name255LengthConstraint {
            get {
                return ResourceManager.GetString("Name255LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdi kan ikke overstige 50 tegn.
        /// </summary>
        public static string Name50LengthConstraint {
            get {
                return ResourceManager.GetString("Name50LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdi er påkrevet.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prisen er ikke-null verdi.
        /// </summary>
        public static string NeedPriceNonZeroValue {
            get {
                return ResourceManager.GetString("NeedPriceNonZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternativ fra admin.
        /// </summary>
        public static string OtherActiveCourseAlternative {
            get {
                return ResourceManager.GetString("OtherActiveCourseAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Betalt.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pris.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pris er påkrevet.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Klar for faktura.
        /// </summary>
        public static string ReadyForInvoiced {
            get {
                return ResourceManager.GetString("ReadyForInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kurs.
        /// </summary>
        public static string SelectedAlternativeByAdmin {
            get {
                return ResourceManager.GetString("SelectedAlternativeByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valgt av admin.
        /// </summary>
        public static string SelectedByAdmin {
            get {
                return ResourceManager.GetString("SelectedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send sms til kunden.
        /// </summary>
        public static string SendSMSToCustomer {
            get {
                return ResourceManager.GetString("SendSMSToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sms meldingstekst.
        /// </summary>
        public static string SmsText {
            get {
                return ResourceManager.GetString("SmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start er påkrevet.
        /// </summary>
        public static string StartRequired {
            get {
                return ResourceManager.GetString("StartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopp.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopp er påkrevet.
        /// </summary>
        public static string StopRequired {
            get {
                return ResourceManager.GetString("StopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil 1.
        /// </summary>
        public static string Telephone1 {
            get {
                return ResourceManager.GetString("Telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mobil 2.
        /// </summary>
        public static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tekst verdi kan ikke overstige 160 tegn..
        /// </summary>
        public static string Text160LengthConstraint {
            get {
                return ResourceManager.GetString("Text160LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tekst er påkrevet.
        /// </summary>
        public static string TextIsRequered {
            get {
                return ResourceManager.GetString("TextIsRequered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tid.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Til dato.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Til dato er påkrevet.
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verdien må være sifret.
        /// </summary>
        public static string ValueMustBeInt {
            get {
                return ResourceManager.GetString("ValueMustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukedag.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukedager.
        /// </summary>
        public static string Weekdays {
            get {
                return ResourceManager.GetString("Weekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-post er ikke gyldig.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feil periode.
        /// </summary>
        public static string WrongPeriod {
            get {
                return ResourceManager.GetString("WrongPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feil tid.
        /// </summary>
        public static string WrongTime {
            get {
                return ResourceManager.GetString("WrongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postnr.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postnr er påkrevet.
        /// </summary>
        public static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
    }
}
