//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long RowId { get; set; }
        public string userId { get; set; }
        public System.DateTime Datetime { get; set; }
        public string IP { get; set; }
        public string userAgent { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
