//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFilterSettings2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderFilterSettings2()
        {
            this.OrderFilters = new HashSet<OrderFilters>();
        }
    
        public int Id { get; set; }
        public string NameFilter { get; set; }
        public Nullable<int> PriorityType { get; set; }
        public double DeltaDateBeg { get; set; }
        public double DeltaDateEnd { get; set; }
        public double DeltaDateBegEx { get; set; }
        public double DeltaDateEndEx { get; set; }
        public bool UseStatusFilter { get; set; }
        public bool UseCreatorFilter { get; set; }
        public bool UseExecuterFilter { get; set; }
        public bool UseTypeFilter { get; set; }
        public bool UseClientFilter { get; set; }
        public bool UsePriorityFilter { get; set; }
        public bool UseDateFilter { get; set; }
        public bool UseExDateFilter { get; set; }
        public string IdCurrentUser { get; set; }
        public Nullable<bool> UseOrderPayerFilter { get; set; }
        public Nullable<bool> UseOrderOrgFromFilter { get; set; }
        public Nullable<bool> UseOrderOrgToFilter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFilters> OrderFilters { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
