//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPipelineSteps
    {
        public int Id { get; set; }
        public int FromStatus { get; set; }
        public int ToStatus { get; set; }
        public string AccessRoleId { get; set; }
        public Nullable<bool> StartDateForClient { get; set; }
        public Nullable<bool> StartDateForExecuter { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<bool> FinishOfTheProcess { get; set; }
    
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual OrderStatuses OrderStatuses1 { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual OrderTypesBase OrderTypesBase { get; set; }
    }
}
