//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int Id { get; set; }
        public int menuId { get; set; }
        public string roleId { get; set; }
    
        public virtual MenuStructure MenuStructure { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
