//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string City { get; set; }
        public string Photo { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string AdressFrom { get; set; }
        public bool isFinishStatuses { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
