//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessages
    {
        public int Id { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public string MessageText { get; set; }
        public string CreatedFromUser { get; set; }
        public string CreatedToUser { get; set; }
        public string MessageSubject { get; set; }
        public Nullable<System.DateTime> DateTimeOpen { get; set; }
        public Nullable<long> OrderId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
