//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corum.Models.ViewModels.ModelsResources", typeof(ModelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern kommentar.
        /// </summary>
        public static string AdminComment {
            get {
                return ResourceManager.GetString("AdminComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse er påkrevet.
        /// </summary>
        public static string AdressRequired {
            get {
                return ResourceManager.GetString("AdressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 1.
        /// </summary>
        public static string Alternative1 {
            get {
                return ResourceManager.GetString("Alternative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 1 er påkrevet.
        /// </summary>
        public static string Alternative1Required {
            get {
                return ResourceManager.GetString("Alternative1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 2.
        /// </summary>
        public static string Alternative2 {
            get {
                return ResourceManager.GetString("Alternative2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beløp.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poststed.
        /// </summary>
        public static string Aria {
            get {
                return ResourceManager.GetString("Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poststed er påkrevet.
        /// </summary>
        public static string AriaRequired {
            get {
                return ResourceManager.GetString("AriaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødselsdato.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødselsdato er påkrevet.
        /// </summary>
        public static string BithdayIsRequired {
            get {
                return ResourceManager.GetString("BithdayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil 1 eiers navn.
        /// </summary>
        public static string Cellphone1ownerName {
            get {
                return ResourceManager.GetString("Cellphone1ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil1 er påkrevet.
        /// </summary>
        public static string Cellphone1Required {
            get {
                return ResourceManager.GetString("Cellphone1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil 2 eiers navn.
        /// </summary>
        public static string Cellphone2ownerName {
            get {
                return ResourceManager.GetString("Cellphone2ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil2 er påkrevet.
        /// </summary>
        public static string Cellphone2Required {
            get {
                return ResourceManager.GetString("Cellphone2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornavn/Etternavn.
        /// </summary>
        public static string ChildName {
            get {
                return ResourceManager.GetString("ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier kursdeltakere.
        /// </summary>
        public static string CopyChildren {
            get {
                return ResourceManager.GetString("CopyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktør er påkrevet.
        /// </summary>
        public static string CourseInstructorRequired {
            get {
                return ResourceManager.GetString("CourseInstructorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktør.
        /// </summary>
        public static string CourseInstructors {
            get {
                return ResourceManager.GetString("CourseInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurssted er påkrevet.
        /// </summary>
        public static string CourseLocationRequired {
            get {
                return ResourceManager.GetString("CourseLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurssted.
        /// </summary>
        public static string CourseLocations {
            get {
                return ResourceManager.GetString("CourseLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursnavn.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursperiode.
        /// </summary>
        public static string CoursePeriods {
            get {
                return ResourceManager.GetString("CoursePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn er påkrevet.
        /// </summary>
        public static string CourseTypeNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CourseTypeNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurstype er påkrevet.
        /// </summary>
        public static string CourseTypeRequired {
            get {
                return ResourceManager.GetString("CourseTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurstype.
        /// </summary>
        public static string CourseTypes {
            get {
                return ResourceManager.GetString("CourseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukedag er påkrevet.
        /// </summary>
        public static string CourseWeekdayRequired {
            get {
                return ResourceManager.GetString("CourseWeekdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornavn/Etternavn.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnr.
        /// </summary>
        public static string CustomerZip {
            get {
                return ResourceManager.GetString("CustomerZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du må velge to forskjellige alternativ.
        /// </summary>
        public static string DifferentAlternatives {
            get {
                return ResourceManager.GetString("DifferentAlternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        public static string EmailMessageBody {
            get {
                return ResourceManager.GetString("EmailMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post er påkrevet.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emne.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feilmelding.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra dato.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra dato er påkrevet.
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimale antallet seter.
        /// </summary>
        public static string MaxSeatsCount {
            get {
                return ResourceManager.GetString("MaxSeatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seter er ikke-null verdi.
        /// </summary>
        public static string MaxSeatsCountRequired {
            get {
                return ResourceManager.GetString("MaxSeatsCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdi kan ikke overstige 10 tegn.
        /// </summary>
        public static string Name10LengthConstraint {
            get {
                return ResourceManager.GetString("Name10LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdi kan ikke overstige 20 tegn.
        /// </summary>
        public static string Name20LengthConstraint {
            get {
                return ResourceManager.GetString("Name20LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdi kan ikke overstige 255 tegn.
        /// </summary>
        public static string Name255LengthConstraint {
            get {
                return ResourceManager.GetString("Name255LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdi kan ikke overstige 50 tegn.
        /// </summary>
        public static string Name50LengthConstraint {
            get {
                return ResourceManager.GetString("Name50LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdi er påkrevet.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisen er ikke-null verdi.
        /// </summary>
        public static string NeedPriceNonZeroValue {
            get {
                return ResourceManager.GetString("NeedPriceNonZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ fra admin.
        /// </summary>
        public static string OtherActiveCourseAlternative {
            get {
                return ResourceManager.GetString("OtherActiveCourseAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalt.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris er påkrevet.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klar for faktura.
        /// </summary>
        public static string ReadyForInvoiced {
            get {
                return ResourceManager.GetString("ReadyForInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string SelectedAlternativeByAdmin {
            get {
                return ResourceManager.GetString("SelectedAlternativeByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgt av admin.
        /// </summary>
        public static string SelectedByAdmin {
            get {
                return ResourceManager.GetString("SelectedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send sms til kunden.
        /// </summary>
        public static string SendSMSToCustomer {
            get {
                return ResourceManager.GetString("SendSMSToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms meldingstekst.
        /// </summary>
        public static string SmsText {
            get {
                return ResourceManager.GetString("SmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start er påkrevet.
        /// </summary>
        public static string StartRequired {
            get {
                return ResourceManager.GetString("StartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp er påkrevet.
        /// </summary>
        public static string StopRequired {
            get {
                return ResourceManager.GetString("StopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil 1.
        /// </summary>
        public static string Telephone1 {
            get {
                return ResourceManager.GetString("Telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil 2.
        /// </summary>
        public static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst verdi kan ikke overstige 160 tegn..
        /// </summary>
        public static string Text160LengthConstraint {
            get {
                return ResourceManager.GetString("Text160LengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst er påkrevet.
        /// </summary>
        public static string TextIsRequered {
            get {
                return ResourceManager.GetString("TextIsRequered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til dato.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til dato er påkrevet.
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien må være sifret.
        /// </summary>
        public static string ValueMustBeInt {
            get {
                return ResourceManager.GetString("ValueMustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukedag.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukedager.
        /// </summary>
        public static string Weekdays {
            get {
                return ResourceManager.GetString("Weekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post er ikke gyldig.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil periode.
        /// </summary>
        public static string WrongPeriod {
            get {
                return ResourceManager.GetString("WrongPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil tid.
        /// </summary>
        public static string WrongTime {
            get {
                return ResourceManager.GetString("WrongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnr.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnr er påkrevet.
        /// </summary>
        public static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
    }
}
