
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class AdditionalRoutePoints
{

    public long Id { get; set; }

    public long RoutePointId { get; set; }

    public Nullable<bool> IsLoading { get; set; }

    public long OrderId { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonPhone { get; set; }

    public Nullable<int> NumberPoint { get; set; }



    public virtual OrdersBase OrdersBase { get; set; }

    public virtual Organization Organization { get; set; }

}

}
