//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketDocuments
    {
        public int IdBucketDocument { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocNumber { get; set; }
        public string CreatedBy { get; set; }
    }
}
