//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketDocumentRows
    {
        public int Id { get; set; }
        public int IdBucketDocument { get; set; }
        public string InnerPartyKey { get; set; }
        public string Storage { get; set; }
        public string Product { get; set; }
        public string Shifr { get; set; }
        public string Shifr_MDM { get; set; }
        public string BacodeConsignment { get; set; }
        public string BacodeProduct { get; set; }
        public string StorageCode { get; set; }
        public string Comments { get; set; }
        public int Count { get; set; }
    }
}
