//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketDocumentRows
    {
        public int Id { get; set; }
        public int IdBucketDocument { get; set; }
        public string InnerPartyKey { get; set; }
        public string Storage { get; set; }
        public string Product { get; set; }
        public string Shifr { get; set; }
        public string Shifr_MDM { get; set; }
        public string BacodeConsignment { get; set; }
        public string BacodeProduct { get; set; }
        public string StorageCode { get; set; }
        public string Comments { get; set; }
        public int Count { get; set; }
        public string BalanceKeeper { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
    }
}
