
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class ConcursDiscountRate
{

    public int Id { get; set; }

    public Nullable<decimal> DiscountRate { get; set; }

    public Nullable<System.DateTime> DateBeg { get; set; }

    public Nullable<System.DateTime> DateEnd { get; set; }

}

}
