
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Contracts
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contracts()
    {

        this.ContractGroupesSpecifications = new HashSet<ContractGroupesSpecifications>();

        this.OrderUsedCars = new HashSet<OrderUsedCars>();

        this.OrderUsedCars1 = new HashSet<OrderUsedCars>();

    }


    public int Id { get; set; }

    public Nullable<int> CarOwnersId { get; set; }

    public Nullable<int> BalanceKeeperId { get; set; }

    public string ContractNumber { get; set; }

    public Nullable<System.DateTime> ContractDate { get; set; }

    public Nullable<System.DateTime> DateBeg { get; set; }

    public Nullable<System.DateTime> DateEnd { get; set; }

    public Nullable<int> ExpeditorId { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<int> DaysDelay { get; set; }

    public Nullable<System.DateTime> ReceiveDateReal { get; set; }

    public string ContractRevision { get; set; }

    public Nullable<decimal> NDSTax { get; set; }



    public virtual BalanceKeepers BalanceKeepers { get; set; }

    public virtual CarOwners CarOwners { get; set; }

    public virtual CarOwners CarOwners1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ContractGroupesSpecifications> ContractGroupesSpecifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderUsedCars> OrderUsedCars { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderUsedCars> OrderUsedCars1 { get; set; }

}

}
