//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractGroupesSpecifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractGroupesSpecifications()
        {
            this.ContractSpecifications = new HashSet<ContractSpecifications>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateBeg { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string NameGroupSpec { get; set; }
        public Nullable<int> DaysDelay { get; set; }
        public bool IsActive { get; set; }
        public int ContractId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<decimal> FuelPrice { get; set; }
        public Nullable<decimal> ExchangeRateUahRub { get; set; }
        public Nullable<decimal> NDSTax { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractSpecifications> ContractSpecifications { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
