
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Countries
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Countries()
    {

        this.UserProfile = new HashSet<UserProfile>();

        this.OrdersPassengerTransport = new HashSet<OrdersPassengerTransport>();

        this.OrdersPassengerTransport1 = new HashSet<OrdersPassengerTransport>();

        this.OrderTruckTransport = new HashSet<OrderTruckTransport>();

        this.OrderTruckTransport1 = new HashSet<OrderTruckTransport>();

        this.Organization = new HashSet<Organization>();

    }


    public int Сode { get; set; }

    public string Name { get; set; }

    public string Fullname { get; set; }

    public string alpha2 { get; set; }

    public string alpha3 { get; set; }

    public Nullable<bool> IsDefault { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserProfile> UserProfile { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdersPassengerTransport> OrdersPassengerTransport { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdersPassengerTransport> OrdersPassengerTransport1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderTruckTransport> OrderTruckTransport { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderTruckTransport> OrderTruckTransport1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Organization> Organization { get; set; }

}

}
