
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class ELMAH_Error
{

    public System.Guid ErrorId { get; set; }

    public string Application { get; set; }

    public string Host { get; set; }

    public string Type { get; set; }

    public string Source { get; set; }

    public string Message { get; set; }

    public string User { get; set; }

    public int StatusCode { get; set; }

    public System.DateTime TimeUtc { get; set; }

    public int Sequence { get; set; }

    public string AllXml { get; set; }

}

}
