
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class FAQAnswers
{

    public int Id { get; set; }

    public int GroupId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }



    public virtual FAQGroupes FAQGroupes { get; set; }

}

}
