//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQAnswers
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual FAQGroupes FAQGroupes { get; set; }
    }
}
