
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class LogImportErrors
{

    public Nullable<bool> IsRests { get; set; }

    public Nullable<int> NumRow { get; set; }

    public string ColumnName { get; set; }

    public string CommentError { get; set; }

    public string guidSession { get; set; }

    public Nullable<System.DateTime> DateWriteLog { get; set; }

    public int id { get; set; }

    public Nullable<int> isCommentType { get; set; }

    public Nullable<int> idSnapshot { get; set; }



    public virtual LogisticSnapshots LogisticSnapshots { get; set; }

}

}
