
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class LoginHistory
{

    public long RowId { get; set; }

    public string userId { get; set; }

    public System.DateTime Datetime { get; set; }

    public string IP { get; set; }

    public string userAgent { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
