//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogImportErrors
    {
        public Nullable<bool> IsRests { get; set; }
        public Nullable<int> NumRow { get; set; }
        public string ColumnName { get; set; }
        public string CommentError { get; set; }
        public string guidSession { get; set; }
        public Nullable<System.DateTime> DateWriteLog { get; set; }
        public int id { get; set; }
        public Nullable<int> isCommentType { get; set; }
        public Nullable<int> idSnapshot { get; set; }
    
        public virtual LogisticSnapshots LogisticSnapshots { get; set; }
    }
}
