//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCompetitiveList
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public Nullable<int> CarsAccepted { get; set; }
        public Nullable<decimal> NDS { get; set; }
        public decimal CarCostDog { get; set; }
        public decimal CarCost { get; set; }
        public Nullable<int> DaysDelay { get; set; }
        public Nullable<int> Prepayment { get; set; }
        public Nullable<decimal> PrepaymentEffect { get; set; }
        public string Comments { get; set; }
        public string ExpeditorName { get; set; }
        public Nullable<decimal> CarryCapacity { get; set; }
        public Nullable<bool> IsSelectedId { get; set; }
        public Nullable<decimal> Prepayment2 { get; set; }
        public Nullable<decimal> PrepaymentEffect2 { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<int> GenId { get; set; }
        public Nullable<int> CarsOffered { get; set; }
        public Nullable<decimal> CarCost7 { get; set; }
        public Nullable<int> DaysDelayStep1 { get; set; }
        public Nullable<int> DaysDelayStep2 { get; set; }
        public Nullable<int> tenderNumber { get; set; }
        public string itemDescription { get; set; }
        public string cargoWeight { get; set; }
    
        public virtual ContractSpecifications ContractSpecifications { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
    }
}
