
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class OrderConcursListsSteps
{

    public long Id { get; set; }

    public int StepId { get; set; }

    public Nullable<System.DateTime> Datetimevalue { get; set; }

    public string UserId { get; set; }

    public Nullable<long> OrderId { get; set; }



    public virtual OrderConcursSteps OrderConcursSteps { get; set; }

    public virtual OrdersBase OrdersBase { get; set; }

    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
