//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAttachments
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string DocDescription { get; set; }
        public string AddedByUser { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public int DocType { get; set; }
        public byte[] DocBody { get; set; }
        public string RealFileName { get; set; }
    
        public virtual OrdersDocTypes OrdersDocTypes { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
