//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConcursListsSteps
    {
        public long Id { get; set; }
        public int StepId { get; set; }
        public Nullable<System.DateTime> Datetimevalue { get; set; }
        public string UserId { get; set; }
        public Nullable<long> OrderId { get; set; }
    
        public virtual OrderConcursSteps OrderConcursSteps { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
