//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderUsedCars
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string CarOwnerInfo { get; set; }
        public string CarModelInfo { get; set; }
        public string CarRegNum { get; set; }
        public string CarDriverInfo { get; set; }
        public string DriverContactInfo { get; set; }
        public string CarrierInfo { get; set; }
        public Nullable<int> CarId { get; set; }
        public string ContractInfo { get; set; }
        public string ExpeditorName { get; set; }
        public Nullable<decimal> Summ { get; set; }
        public string DriverCardInfo { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CarCapacity { get; set; }
        public Nullable<decimal> PlanDistance { get; set; }
        public Nullable<int> PlanTimeWorkDay { get; set; }
        public Nullable<int> PlanTimeHoliday { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> BaseRateWorkDay { get; set; }
        public Nullable<decimal> BaseRateHoliday { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public Nullable<int> ExpeditorId { get; set; }
        public Nullable<int> ContractExpBkId { get; set; }
        public Nullable<System.DateTime> FactShipperDateTime { get; set; }
        public Nullable<System.DateTime> FactConsigneeDateTime { get; set; }
        public Nullable<System.DateTime> FactConsignee { get; set; }
        public Nullable<System.DateTime> FactShipper { get; set; }
        public Nullable<System.Guid> formUuid { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public string trailerNumber { get; set; }
        public string transportDimensions { get; set; }
        public Nullable<double> distance { get; set; }
        public string stateBorderCrossingPoint { get; set; }
        public string seriesPassportNumber { get; set; }
        public string drivingLicenseNumber { get; set; }
        public Nullable<int> tenderNumber { get; set; }
        public Nullable<int> fullMassTC { get; set; }
        public Nullable<int> massWithoutLoadTC1 { get; set; }
        public Nullable<int> fullMassTC2Trailer { get; set; }
        public Nullable<int> massWithoutLoadTC2Trailer { get; set; }
        public Nullable<double> Summ_ { get; set; }
    
        public virtual CarOwners CarOwners { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual Contracts Contracts1 { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
    }
}
