//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBaseSpecification
    {
        public int Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
    
        public virtual SpecificationTypes SpecificationTypes { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
    }
}
