//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTruckTransport
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public int TruckTypeId { get; set; }
        public string TruckDescription { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string BoxingDescription { get; set; }
        public Nullable<decimal> DimenssionL { get; set; }
        public Nullable<decimal> DimenssionW { get; set; }
        public Nullable<decimal> DimenssionH { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> LoadingTypeId { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public Nullable<System.DateTime> FromShipperDatetime { get; set; }
        public Nullable<System.DateTime> ToConsigneeDatetime { get; set; }
        public Nullable<int> UnloadingTypeId { get; set; }
        public Nullable<int> ShipperCountryId { get; set; }
        public Nullable<int> ConsigneeCountryId { get; set; }
        public string ShipperCity { get; set; }
        public string ConsigneeCity { get; set; }
        public string ShipperAdress { get; set; }
        public string ConsigneeAdress { get; set; }
        public Nullable<int> TripType { get; set; }
        public string ShipperContactPerson { get; set; }
        public string ShipperContactPersonPhone { get; set; }
        public string ConsigneeContactPerson { get; set; }
        public string ConsigneeContactPersonPhone { get; set; }
        public Nullable<long> ShipperId { get; set; }
        public Nullable<long> ConsigneeId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Countries Countries1 { get; set; }
        public virtual OrderLoadingTypes OrderLoadingTypes { get; set; }
        public virtual OrderTruckTypes OrderTruckTypes { get; set; }
        public virtual RouteTypes RouteTypes { get; set; }
        public virtual OrderVehicleTypes OrderVehicleTypes { get; set; }
        public virtual OrderUnloadingTypes OrderUnloadingTypes { get; set; }
        public virtual OrdersBase OrdersBase { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
    }
}
