//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFilters
    {
        public int Id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CreatorId { get; set; }
        public string ExecuterId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<int> OrderFilterSetId { get; set; }
        public Nullable<int> PayerId { get; set; }
        public Nullable<int> OrgFromId { get; set; }
        public Nullable<int> OrgToId { get; set; }
    
        public virtual OrderClients OrderClients { get; set; }
        public virtual OrderFilterSettings2 OrderFilterSettings2 { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual OrderTypesBase OrderTypesBase { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
