
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class OrderStatusHistory
{

    public long Id { get; set; }

    public long OrderId { get; set; }

    public System.DateTime ChangeDateTime { get; set; }

    public string ChangedByUser { get; set; }

    public Nullable<int> OldStatus { get; set; }

    public Nullable<int> NewStatus { get; set; }

    public string StatusChangeComment { get; set; }



    public virtual OrderStatuses OrderStatuses { get; set; }

    public virtual OrderStatuses OrderStatuses1 { get; set; }

    public virtual OrdersBase OrdersBase { get; set; }

    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
