
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class OrderBaseProjects
{

    public int Id { get; set; }

    public long OrderId { get; set; }

    public int ProjectId { get; set; }



    public virtual Projects Projects { get; set; }

    public virtual OrdersBase OrdersBase { get; set; }

}

}
