
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class OrderAttachments
{

    public long Id { get; set; }

    public long OrderId { get; set; }

    public string DocDescription { get; set; }

    public string AddedByUser { get; set; }

    public System.DateTime AddedDateTime { get; set; }

    public int DocType { get; set; }

    public byte[] DocBody { get; set; }

    public string RealFileName { get; set; }



    public virtual OrdersDocTypes OrdersDocTypes { get; set; }

    public virtual OrdersBase OrdersBase { get; set; }

    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
