//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int Id { get; set; }
        public int menuId { get; set; }
        public string roleId { get; set; }
    
        public virtual MenuStructure MenuStructure { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
