
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Projects
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Projects()
    {

        this.OrderBaseProjects = new HashSet<OrderBaseProjects>();

        this.OrdersBase = new HashSet<OrdersBase>();

    }


    public int Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public Nullable<int> ProjectTypeId { get; set; }

    public Nullable<int> ProjectCFOId { get; set; }

    public string ProjectOrderer { get; set; }

    public string ConstructionDesc { get; set; }

    public string Comments { get; set; }

    public Nullable<int> PlanCount { get; set; }

    public Nullable<bool> isActive { get; set; }

    public string ManufacturingEnterprise { get; set; }

    public Nullable<int> NumOrder { get; set; }

    public Nullable<System.DateTime> DateOpenOrder { get; set; }

    public Nullable<System.DateTime> PlanPeriodForMP { get; set; }

    public Nullable<System.DateTime> PlanPeriodForComponents { get; set; }

    public Nullable<System.DateTime> PlanPeriodForSGI { get; set; }

    public Nullable<System.DateTime> PlanPeriodForTransportation { get; set; }

    public Nullable<System.DateTime> PlanDeliveryToConsignee { get; set; }

    public string DeliveryBasic { get; set; }

    public Nullable<long> Shipper { get; set; }

    public Nullable<long> Consignee { get; set; }



    public virtual Centers Centers { get; set; }

    public virtual ProjectTypes ProjectTypes { get; set; }

    public virtual Projects Projects1 { get; set; }

    public virtual Projects Projects2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderBaseProjects> OrderBaseProjects { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdersBase> OrdersBase { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Organization Organization1 { get; set; }

}

}
