//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterMessageToContragents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterMessageToContragents()
        {
            this.RegisterFormFromContragents = new HashSet<RegisterFormFromContragents>();
        }
    
        public int Id { get; set; }
        public long orderId { get; set; }
        public int tenderNumber { get; set; }
        public string contragentName { get; set; }
        public string emailOperacionist { get; set; }
        public string emailContragent { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public string descriptionTender { get; set; }
        public Nullable<int> acceptedTransportUnits { get; set; }
        public Nullable<double> cost { get; set; }
        public System.Guid tenderItemUuid { get; set; }
        public System.Guid formUuid { get; set; }
        public int industryId { get; set; }
        public Nullable<bool> flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterFormFromContragents> RegisterFormFromContragents { get; set; }
    }
}
