//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterFormFromContragents
    {
        public int Id { get; set; }
        public int RegisterMessageToContragentId { get; set; }
        public string carBrand { get; set; }
        public string stateNumberCar { get; set; }
        public string trailerNumber { get; set; }
        public Nullable<double> loadCapacity { get; set; }
        public Nullable<double> distance { get; set; }
        public string fullNameOfDriver { get; set; }
        public string phoneNumber { get; set; }
        public string drivingLicenseNumber { get; set; }
        public string contragentName { get; set; }
        public string note { get; set; }
        public string stateBorderCrossingPoint { get; set; }
        public string seriesPassportNumber { get; set; }
        public Nullable<bool> scannedCopyOfSignedOrder { get; set; }
        public Nullable<bool> scannedCopyOfRegistrationCertificate { get; set; }
        public Nullable<bool> scanCopyOfPassport { get; set; }
        public Nullable<bool> scannedCopyOfAdmissionToTransportation { get; set; }
        public Nullable<bool> scannedCopyOfCivilPassport { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public System.Guid tenderItemUuid { get; set; }
        public string transportDimensions { get; set; }
        public Nullable<int> fullMassTC { get; set; }
        public Nullable<int> massWithoutLoadTC1 { get; set; }
        public Nullable<int> fullMassTC2Trailer { get; set; }
        public Nullable<int> massWithoutLoadTC2Trailer { get; set; }
        public Nullable<bool> filesTTH_CMR { get; set; }
        public Nullable<bool> filesInvoice { get; set; }
        public Nullable<bool> filesActOfCompletion { get; set; }
    
        public virtual RegisterMessageToContragents RegisterMessageToContragents { get; set; }
    }
}
