
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Corum.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class RoutePoints
{

    public int Id { get; set; }

    public Nullable<long> RoutePointId { get; set; }

    public Nullable<int> RoutePointTypeId { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonPhone { get; set; }

    public Nullable<int> NumberPoint { get; set; }

    public Nullable<long> OrganizationId { get; set; }



    public virtual RoutePointType RoutePointType { get; set; }

    public virtual Routes Routes { get; set; }

    public virtual Organization Organization { get; set; }

}

}
