//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePoints
    {
        public int Id { get; set; }
        public Nullable<long> RoutePointId { get; set; }
        public Nullable<int> RoutePointTypeId { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public Nullable<int> NumberPoint { get; set; }
        public Nullable<long> OrganizationId { get; set; }
    
        public virtual RoutePointType RoutePointType { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
