//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corum.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string City { get; set; }
        public string Photo { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string AdressFrom { get; set; }
        public bool isFinishStatuses { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
